[package]
name = "orchid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
chumsky = "0.8"
derivative = "2.2"
hashbrown = "0.12"
mappable-rc = "0.1"
ordered-float = "3.0"
itertools = "0.10"
smallvec = { version = "1.10.0", features = ['const_generics'] }
lazy_static = "1.4.0"
