[workspace]
resolver = "2"

members = [
  # "orchidlang",
  "orcx",
  "orchid-api",
  "orchid-std", "orchid-base", "orchid-api-derive", "orchid-api-traits", "stdio-perftest", "orchid-extension", "orchid-host",
]
