[package]
name = "orchidlang"
version = "0.2.2"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/lbfalvy/orchid"
description = """
An embeddable pure functional scripting language
"""
authors = [
  "Lawrence Bethlenfalvy <lbfalvy@protonmail.com>"
]

[lib]
path = "src/lib.rs"

[[bin]]
name = "orcx"
path = "src/bin/main.rs"
doc = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
chumsky = "0.9.2"
hashbrown = "0.13.2"
ordered-float = "3.0"
itertools = "0.10"
dyn-clone = "1.0.11"
clap = { version = "4.2.4", features = ["derive"] }
trait-set = "0.3.0"
