[package]
name = "orchid"
version = "0.2.1"
edition = "2021"
authors = [
  "Lawrence Bethlenfalvy <lbfalvy@protonmail.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
chumsky = "0.9.2"
hashbrown = "0.13.2"
ordered-float = "3.0"
itertools = "0.10"
smallvec = { version = "1.10.0", features = ['const_generics'] }
dyn-clone = "1.0.11"
clap = { version = "4.2.4", features = ["derive"] }
