[package]
name = "orchid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
chumsky = "0.9.2"
hashbrown = "0.13.2"
mappable-rc = "0.1"
ordered-float = "3.0"
itertools = "0.10"
smallvec = { version = "1.10.0", features = ['const_generics'] }
dyn-clone = "1.0.11"
lasso = { version = "0.6.0", features = ['multi-threaded'] }
