[package]
name = "orchid"
version = "0.2.0"
edition = "2021"
authors = [
  "Lawrence Bethlenfalvy <lbfalvy@protonmail.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
chumsky = "0.9.2"
hashbrown = "0.13.2"
mappable-rc = "0.1"
ordered-float = "3.0"
itertools = "0.10"
smallvec = { version = "1.10.0", features = ['const_generics'] }
dyn-clone = "1.0.11"
lasso = { version = "0.6.0", features = ['multi-threaded'] }
base64 = "0.21.0"
static_init = "1.0.3"
clap = { version = "4.2.7", features = ["derive"] }
